spring:
  # 配置数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/博客名?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  # 配置email
  mail:
    host: smtp.qq.com
    username: test@qq.com
    password: root
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
  # 配置redis
  redis:
    host: localhost
    port: 6379
    password: root
  # 配置 rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # 配置 elasticsearch
  elasticsearch:
    rest:
      uris: http://localhost:9200
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 20MB
      # 上传文件的总大小值
      max-request-size: 80MB

# 配置mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 配置七牛密钥
qiniu:
  url: 
  bucketName: 
  accessKey: 
  accessSecretKey: 

# 网站前台域名（邮件通知用）
website:
  url: https://www.hdiata.com/

# 搜索模式( mysql 或 elasticsearch )
search:
  mode: mysql